services:
  postgres:
    image: postgres:16
    container_name: flashbox_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - flashbox_postgres_data:/var/lib/postgresql/data

volumes:
  flashbox_postgres_data:
